// AUTO-GENERATED by apps/web/scripts/build-axe-translations.mjs — do not edit.
// Source: axe-core 4.11.4 + axe-core/locales/de.json
// Re-run after upgrading axe-core in apps/scanner.

const HELP_EN_TO_DE = new Map<string, string>([
  [`accesskey attribute value should be unique`, `Der Wert des accesskey-Attributes muss einzigartig sein.`],
  [`Active <area> elements must have alternative text`, `Aktive <area>-Elemente müssen einen Alternativtext besitzen.`],
  [`Elements must only use supported ARIA attributes`, `Elemente dürfen nur erlaubte ARIA-Attribute verwenden.`],
  [`ARIA role should be appropriate for the element`, `Der Wert des role-Attributes muss für dieses Element geeignet sein.`],
  [`aria-braille attributes must have a non-braille equivalent`, `aria-braille Attribute müssen ein non-braille Äquivalent haben.`],
  [`ARIA commands must have an accessible name`, `ARIA Befehle müssen einen zugänglichen Namen (accessible name) besitzen.`],
  [`ARIA attributes must be used as specified for the element's role`, `ARIA-Attribute müssen entsprechend der Rolle des Elements verwendet werden.`],
  [`Deprecated ARIA roles must not be used`, `Veraltete ARIA-Rollen dürfen nicht verwendet werden.`],
  [`ARIA dialog and alertdialog nodes should have an accessible name`, `ARIA-dialog und -alertdialog Knoten müssen einen zugänglichen Namen (accessible name) besitzen.`],
  [`aria-hidden="true" must not be present on the document body`, `Aria-hidden='true' darf nicht für den <body> des Dokumentes verwendet werden.`],
  [`ARIA hidden element must not be focusable or contain focusable elements`, `ARIA-hidden Elemente dürfen keine fokussierbaren Elemente beinhalten.`],
  [`ARIA input fields must have an accessible name`, `ARIA-inputs müssen einen zugänglichen Namen (accessible name) besitzen.`],
  [`ARIA meter nodes must have an accessible name`, `ARIA-meter Knoten müssen einen zugänglichen Namen (accessible name) besitzen.`],
  [`ARIA progressbar nodes must have an accessible name`, `ARIA-progressbar Knoten müssen einen zugänglichen Namen (accessible name) besitzen.`],
  [`Elements must only use permitted ARIA attributes`, `Elemente dürfen nur erlaubte ARIA-Attribute verwenden.`],
  [`Required ARIA attributes must be provided`, `Erforderliche ARIA-Attribute müssen bereitgestellt werden.`],
  [`Certain ARIA roles must contain particular children`, `Bestimmte ARIA-Rollen müssen spezifische, untergeordnete Kind-Rollen enthalten.`],
  [`Certain ARIA roles must be contained by particular parents`, `Bestimmte ARIA-Rollen müssen in spezifischen, übergeordneten Eltern-Rollen enthalten sein.`],
  [`aria-roledescription must be on elements with a semantic role`, `Nutze aria-roledescription für Elemente mit einer semantischen Rolle.`],
  [`ARIA roles used must conform to valid values`, `Verwendete ARIA-Rollen müssen gültigen Werten entsprechen.`],
  [`"role=text" should have no focusable descendants`, `"role=text" sollte keine fokussierbaren Nachkommen (descendants) haben.`],
  [`ARIA toggle fields must have an accessible name`, `ARIA-toggle-Felder benötigen einen zugänglichen Namen (accessible name).`],
  [`ARIA tooltip nodes must have an accessible name`, `ARIA-tooltip-Knoten benötigen einen zugänglichen Namen (accessible name).`],
  [`ARIA treeitem nodes should have an accessible name`, `ARIA-treeitem-Knoten benötigen einen zugänglichen Namen (accessible name).`],
  [`ARIA attributes must conform to valid values`, `Verwendete ARIA-Attribute müssen gültigen Werten entsprechen.`],
  [`ARIA attributes must conform to valid names`, `Verwendete ARIA-Attribute müssen gültigen Namen entsprechen.`],
  [`<audio> elements must have a captions track`, `<audio>-Elemente müssen eine Untertitelung (captions track) besitzen.`],
  [`autocomplete attribute must be used correctly`, `autocomplete-Attribute müssen korrekt genutzt werden.`],
  [`Inline text spacing must be adjustable with custom stylesheets`, `Zeichenabstände müssen durch benutzerdefinierte Stylesheets anpassbar sein.`],
  [`<blink> elements are deprecated and must not be used`, `<blink>-Elemente sind veraltet und dürfen nicht verwendet werden.`],
  [`Buttons must have discernible text`, `Schaltflächen müssen wahrnehmbaren Text enthalten.`],
  [`Page must have means to bypass repeated blocks`, `Wiederholende Blöcke müssen vom Nutzer mit Hilfe von der Seite bereitgestellten Mitteln übersprungen werden können.`],
  [`Elements must meet enhanced color contrast ratio thresholds`, `Elemente müssen einen ausreichenden Farbkontrast haben.`],
  [`Elements must meet minimum color contrast ratio thresholds`, `Elemente müssen einen ausreichenden Farbkontrast haben.`],
  [`CSS Media queries must not lock display orientation`, `CSS Media Queries dürfen nicht genutzt werden um die Bildschirmausrichtung zu sperren.`],
  [`<dl> elements must only directly contain properly-ordered <dt> and <dd> groups, <script>, <template> or <div> elements`, `<dl>-Elemente dürfen unmittelbar nur korrekt verschachtelte <dt>- und <dd>-Gruppen, <script>- oder <template>-Elemente enthalten.`],
  [`<dt> and <dd> elements must be contained by a <dl>`, `<dt>- und <dd>-Elemente müssen in einem <dl>-Element enthalten sein.`],
  [`Documents must have <title> element to aid in navigation`, `Dokumente müssen ein <title>-Element besitzen, um die Navigation zu erleichtern.`],
  [`IDs of active elements must be unique`, `IDs von aktiven Elementen müssen einzigartig sein.`],
  [`IDs used in ARIA and labels must be unique`, `IDs, welche in ARIA und Lables genutzt werden, müssen einzigartig sein.`],
  [`id attribute value must be unique`, `Der Wert des id-Attributes muss einzigartig sein.`],
  [`Headings should not be empty`, `Überschriften dürfen nicht leer sein.`],
  [`Table header text should not be empty`, `Tabellenkopfzeilen sollten nicht leer sein.`],
  [`Elements in the focus order should have an appropriate role`, `Elemente in der Fokusreihenfolge benötigen eine Rolle, die für interaktive Elemente geeignet ist.`],
  [`Form field must not have multiple label elements`, `form-Felder sollten nur ein label-Element besitzen.`],
  [`Frames with focusable content must not have tabindex=-1`, `Frames mit fokussierbarem Inhalt dürfen keinen tabindex=-1 haben.`],
  [`Frames should be tested with axe-core`, `Frames müssen mit axe-core getestet werden.`],
  [`Frames must have a unique title attribute`, `Frames müssen ein einzigartiges title-Attribut besitzen.`],
  [`Frames must have an accessible name`, `Frames müssen ein nichtleeres title-Attribut besitzen.`],
  [`Heading levels should only increase by one`, `Überschriftenebenen sollten nur jeweils um eins steigen.`],
  [`Hidden content on the page should be analyzed`, `Versteckter Inhalt auf der Seite konnte nicht analysiert werden.`],
  [`<html> element must have a lang attribute`, `Das <html>-Element muss ein lang-Attribut besitzen.`],
  [`<html> element must have a valid value for the lang attribute`, `Das <html>-Element muss einen gültigen Attributwert für das lang-Attribut besitzen.`],
  [`HTML elements with lang and xml:lang must have the same base language`, `HTML Elemente mit lang und xml:lang Attributen müssen dieselbe Sprache ausweisen.`],
  [`Links with the same name must have a similar purpose`, `Links mit dem selben zugänglichen Namen (accessible name) verfolgen denselben Zweck.`],
  [`Images must have alternative text`, `Abbildungen müssen einen Alternativtext besitzen.`],
  [`Alternative text of images should not be repeated as text`, `Der Alternativtext von Bildern sollte nicht als Text wiederholt werden.`],
  [`Input buttons must have discernible text`, `Eingabeschaltflächen müssen wahrnehmbaren Text beinhalten.`],
  [`Image buttons must have alternative text`, `<input type="image">-Elemente müssen einen Alternativtext besitzen.`],
  [`Elements must have their visible text as part of their accessible name`, `Elemente müssen ihren sichtbaren Text auch als Teil des zugänglichen Namens (accessible name) haben.`],
  [`Form elements should have a visible label`, `<form>-Elemente sollten eine sichtbare Beschriftung haben.`],
  [`Form elements must have labels`, `<form>-Elemente müssen eine Beschriftung haben.`],
  [`Banner landmark should not be contained in another landmark`, `Banner landmark muss sich auf der obersten Ebene befinden.`],
  [`Aside should not be contained in another landmark`, `Das aside-Elemente darf sich nicht in einer anderen landmark befinden.`],
  [`Contentinfo landmark should not be contained in another landmark`, `Contentinfo landmark muss sich auf der obersten Ebene befinden.`],
  [`Main landmark should not be contained in another landmark`, `Main landmark ist nicht auf der obersten Ebene.`],
  [`Document should not have more than one banner landmark`, `Das Dokument sollte höchstens eine banner landmark enthalten.`],
  [`Document should not have more than one contentinfo landmark`, `Das Dokument sollte höchstens eine contentinfo landmark enthalten.`],
  [`Document should not have more than one main landmark`, `Das Dokument sollte nur eine main landmark besitzen.`],
  [`Document should have one main landmark`, `Seite muss eine main landmark enthalten.`],
  [`Landmarks should have a unique role or role/label/title (i.e. accessible name) combination`, `Landmarks müssen eine einzigartige role oder role/label/title Kombination (bzw. zugänglicher Name / accessible name) besitzen.`],
  [`Links must be distinguishable without relying on color`, `Links müssen vom umgebenden Text auf eine Weise unterschieden werden können, die nicht allein auf Farbe beruht.`],
  [`Links must have discernible text`, `Links müssen wahrnehmbaren Text beinhalten.`],
  [`<ul> and <ol> must only directly contain <li>, <script> or <template> elements`, `<ul>- und <ol>-Elemente dürfen unmittelbar nur <li>-, <script>- oder <template>-Elemente enthalten.`],
  [`<li> elements must be contained in a <ul> or <ol>`, `<li>-Elemente müssen in einem <ul>- oder <ol>-Element enthalten sein.`],
  [`<marquee> elements are deprecated and must not be used`, `<marquee>-Elemente sind veraltet und dürfen nicht verwendet werden.`],
  [`Delayed refresh must not be used`, `Die verzögerte Aktualisierung darf nicht verwendet werden.`],
  [`Delayed refresh under 20 hours must not be used`, `Eine zeitgesteuerte Aktualisierung (refresh) sollte nicht verwendet werden.`],
  [`Users should be able to zoom and scale the text up to 500%`, `Benutzer sollten in der Lage sein, den Text um bis zu 500% vergrößern und skalieren zu können.`],
  [`Zooming and scaling must not be disabled`, `Zoomen und Skalieren darf nicht deaktiviert werden.`],
  [`Interactive controls must not be nested`, `Interaktive Steuerelemente dürfen nicht verschachtelt (nested) werden.`],
  [`<video> or <audio> elements must not play automatically`, `<video> oder <audio> Elemente geben keine Töne automatisch aus.`],
  [`<object> elements must have alternative text`, `<object>-Elemente müssen einen Alternativtext besitzen.`],
  [`Styled <p> elements must not be used as headings`, `Die Schriftschnitte bold und italic sowie die Schriftgröße dürfen nicht verwendet werden, um <p>-Elemente wie Überschriften zu formatieren.`],
  [`Page should contain a level-one heading`, `Die Seite muss eine Überschrift der ersten Ebene enthalten.`],
  [`Elements marked as presentational should be consistently ignored`, `Elemente mit "role=none" oder "role=presentation" sollen von Screenreadern ignoriert werden.`],
  [`All page content should be contained by landmarks`, `Inhalte sollten in einer landmark region enthalten sein.`],
  [`[role="img"] elements must have alternative text`, `[role='img'] Elemente haben ein Alternativtext.`],
  [`scope attribute should be used correctly`, `Das scope-Attribut sollte korrekt verwendet werden.`],
  [`Scrollable region must have keyboard access`, `Scrollbare Regionen müssen per Tastatur erreichbar sein.`],
  [`Select element must have an accessible name`, `<select> Elemente müssen einen zugänglichen Namen (accessible name) besitzen.`],
  [`Server-side image maps must not be used`, `Serverseitige Imagemaps dürfen nicht verwendet werden.`],
  [`The skip-link target should exist and be focusable`, `Das Ziel eines Skip-Links sollte existieren und fokussierbar sein.`],
  [`Summary elements must have discernible text`, `summary-Elemente müssen einen erkennbaren Text haben`],
  [`<svg> elements with an img role must have alternative text`, `<svg> Elemente mit einer img Rolle sollten einen Alternativtext besitzen.`],
  [`Elements should not have tabindex greater than zero`, `Elemente sollten keinen tabindex besitzen, der größer als null ist.`],
  [`Tables should not have the same summary and caption`, `Das <caption>-Element sollte nicht den gleichen Text wie das summary-Attribut enthalten.`],
  [`Data or header cells must not be used to give caption to a data table.`, `Daten- oder Kopfzellen sollten nicht verwendet werden, um einer Datentabelle eine Überschrift zu geben.`],
  [`All touch targets must be 24px large, or leave sufficient space`, `Alle Berührungsobjekte (touch targets) müssen 24 Pixel groß sein oder ausreichend Platz lassen.`],
  [`Non-empty <td> elements in larger <table> must have an associated table header`, `In Tabellen, die größer als 3 mal 3 sind, müssen alle nichtleeren <td>-Elemente einen zugehörigen Tabellenkopf haben.`],
  [`Table cell headers attributes must refer to other <th> elements in the same table`, `Innerhalb eines <table>-Elementes dürfen sich Zellen, die das headers-Attribut verwenden, nur auf andere Zellen derselben Tabelle beziehen.`],
  [`Table headers in a data table must refer to data cells`, `Alle <th>-Elemente sowie Elemente mit role=columnheader/rowheader müssen Datenzellen haben, die sie beschreiben.`],
  [`lang attribute must have a valid value`, `Das lang-Attribut muss einen gültigen Wert haben.`],
  [`<video> elements must have captions`, `<video>-Elemente müssen Untertitel besitzen.`],
]);

const DESCRIPTION_EN_TO_DE = new Map<string, string>([
  [`Ensure every accesskey attribute value is unique`, `Stellt sicher, dass die Werte der accesskey-Attribute einzigartig sind.`],
  [`Ensure <area> elements of image maps have alternative text`, `Stellt sicher, dass <area>-Elemente Alternativtexte besitzen.`],
  [`Ensure an element's role supports its ARIA attributes`, `Stellt sicher, dass ARIA-Attribute für die vergebene Rolle eines Elements erlaubt sind.`],
  [`Ensure role attribute has an appropriate value for the element`, `Stellt sicher, dass der Wert des role-Attributes für dieses Element geeignet ist.`],
  [`Ensure aria-braillelabel and aria-brailleroledescription have a non-braille equivalent`, `Stellt sicher, dass aria-braillelabel und aria-brailleroledescription ein non-braille Äquivalent haben.`],
  [`Ensure every ARIA button, link and menuitem has an accessible name`, `Stellt sicher, dass jeder ARIA-button, -link und jedes -menuitem einen zugänglichen Namen (accessible name) hat.`],
  [`Ensure ARIA attributes are used as described in the specification of the element's role`, `Stellt sicher, dass ARIA-Attribute wie in der Spezifikation der Rolle des Elements beschrieben verwendet werden.`],
  [`Ensure elements do not use deprecated roles`, `Stellt sicher, dass die Elemente keine veralteten Rollen verwenden.`],
  [`Ensure every ARIA dialog and alertdialog node has an accessible name`, `Stellt sicher, dass jeder ARIA-dialog und -alertdialog Knoten einen zugänglichen Namen (accessible name) hat.`],
  [`Ensure aria-hidden="true" is not present on the document body.`, `Stellt sicher, dass aria-hidden='true' nicht am <body>-Element des Dokumentes verwendet wird.`],
  [`Ensure aria-hidden elements are not focusable nor contain focusable elements`, `Stellt sicher, dass ARIA-hidden Elemente keine fokussierbaren Elemente beinhalten.`],
  [`Ensure every ARIA input field has an accessible name`, `Stellt sicher, dass jeder ARIA-input einen zugänglichen Namen (accessible name) besitzt.`],
  [`Ensure every ARIA meter node has an accessible name`, `Stellt sicher, dass jeder ARIA-meter Knoten einen zugänglichen Namen (accessible name) besitzt.`],
  [`Ensure every ARIA progressbar node has an accessible name`, `Stellt sicher, dass jeder ARIA-progressbar Knoten einen zugänglichen Namen (accessible name) besitzt.`],
  [`Ensure ARIA attributes are not prohibited for an element's role`, `Stellt sicher, dass ARIA-Attribute für die Rolle eines Elements nicht verboten sind.`],
  [`Ensure elements with ARIA roles have all required ARIA attributes`, `Stellt sicher, dass Elemente mit ARIA-Rollen alle erforderlichen ARIA-Attribute besitzen.`],
  [`Ensure elements with an ARIA role that require child roles contain them`, `Stellt sicher, dass Elemente mit einer ARIA-Rolle, welche bestimmte untergeordnete Rollen voraussetzten diese auch enthalten.`],
  [`Ensure elements with an ARIA role that require parent roles are contained by them`, `Stellt sicher, dass Elemente mit ARIA-Rollen, welche übergeordnete Rollen voraussetzen auch in diesen enthalten sind.`],
  [`Ensure aria-roledescription is only used on elements with an implicit or explicit role`, `Stellt sicher, dass ARIA-roledescription nur im Zusammenhang mit einer im- oder expliziten Rolle verwendet wird.`],
  [`Ensure all elements with a role attribute use a valid value`, `Stellt sicher, dass alle Elemente mit einer ARIA-Rolle auch einen gültigen Wert verwenden.`],
  [`Ensure role="text" is used on elements with no focusable descendants`, `Stellt sicher, dass role="text" für Elemente verwendet wird, die keine fokussierbaren Nachkommen (descendants) haben.`],
  [`Ensure every ARIA toggle field has an accessible name`, `Stellt sicher, dass jedes ARIA-toggle-Feld ein zugänglichen Namen (accessible name) besitzt.`],
  [`Ensure every ARIA tooltip node has an accessible name`, `Stellt sicher, dass jeder ARIA-tooltip Knoten einen zugänglichen Namen (accessible name) besitzt.`],
  [`Ensure every ARIA treeitem node has an accessible name`, `Stellt sicher, dass jeder ARIA-treeitem Knoten einen zugänglichen Namen (accessible name) besitzt.`],
  [`Ensure all ARIA attributes have valid values`, `Stellt sicher, dass alle ARIA-Attribute gültige Werte verwenden.`],
  [`Ensure attributes that begin with aria- are valid ARIA attributes`, `Stellt sicher, dass Attribute, welche mit aria- beginnen auch valide ARIA-Attribute sind.`],
  [`Ensure <audio> elements have captions`, `Stellt sicher, dass <audio>-Elemente Untertitel besitzen.`],
  [`Ensure the autocomplete attribute is correct and suitable for the form field`, `Stellt sicher, dass das autocomplete-Attribut korrekt ist und für das form-Feld geeignet ist.`],
  [`Ensure that text spacing set through style attributes can be adjusted with custom stylesheets`, `Stellt sicher, dass der Zeichenabstand durch benutzerdefinierte Stylesheets angepasst werden kann.`],
  [`Ensure <blink> elements are not used`, `Stellt sicher, dass keine <blink>-Elemente verwendet werden.`],
  [`Ensure buttons have discernible text`, `Stellt sicher, dass Schaltflächen wahrnehmbaren Text enthalten.`],
  [`Ensure each page has at least one mechanism for a user to bypass navigation and jump straight to the content`, `Stellt sicher, dass jede Seite mindestens ein Mittel bereitstellt, welches dem Nutzer erlaubt direkt zum Inhalt der Seite zu springen.`],
  [`Ensure the contrast between foreground and background colors meets WCAG 2 AAA enhanced contrast ratio thresholds`, `Stellt sicher, dass der Kontrast zwischen Vorder- und Hintergrundfarbe den in der WCAG 2 als AAA ausgewiesenen Kontrastgrenzwerten entspricht.`],
  [`Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds`, `Stellt sicher, dass der Kontrast zwischen Vorder- und Hintergrundfarbe den in der WCAG 2 als AA ausgewiesenen Kontrastgrenzwerten entspricht.`],
  [`Ensure content is not locked to any specific display orientation, and the content is operable in all display orientations`, `Stellt sicher, dass der Inhalt nicht nur auf einer sondern auf allen spezifischen Bildschirmausrichtungen angezeigt werden kann.`],
  [`Ensure <dl> elements are structured correctly`, `Stellt sicher, dass <dl>-Elemente ordnungsgemäß strukturiert sind.`],
  [`Ensure <dt> and <dd> elements are contained by a <dl>`, `Stellt sicher, dass <dt> und <dd>-Elemente in einem <dl>-Element enthalten sind.`],
  [`Ensure each HTML document contains a non-empty <title> element`, `Stellt sicher, dass jedes HTML-Dokument ein nichtleeres <title>-Element besitzt.`],
  [`Ensure every id attribute value of active elements is unique`, `Stellt sicher, dass jeder Wert des ID-Attributes von aktiven Elemente einzigartig ist.`],
  [`Ensure every id attribute value used in ARIA and in labels is unique`, `Stellt sicher, dass jeder Wert des ID-Attributes, welcher in ARIA und labels genutzt wird einzigartig ist.`],
  [`Ensure every id attribute value is unique`, `Stellt sicher, dass der Wert eines id-Attributes einzigartig ist.`],
  [`Ensure headings have discernible text`, `Stellt sicher, dass Überschriften einen wahrnehmbaren Text beinhalten.`],
  [`Ensure table headers have discernible text`, `Stellt sicher, dass Tabellenkopfzeilen einen wahrnehmbaren Text beinhalten.`],
  [`Ensure elements in the focus order have a role appropriate for interactive content`, `Stellt sicher, dass Elemente in der Fokusreihenfolge eine geeignete Rolle besitzen.`],
  [`Ensure form field does not have multiple label elements`, `Stellt sicher, dass ein form-Feld nur ein label-Element besitzt.`],
  [`Ensure <frame> and <iframe> elements with focusable content do not have tabindex=-1`, `Stellt sicher, dass <frame>- und <iframe>-Elemente mit fokussierbarem Inhalt keinen tabindex=-1 haben.`],
  [`Ensure <iframe> and <frame> elements contain the axe-core script`, `Stellt sicher, dass <iframe> und <frame>-Elemente das axe-core Script beinhalten.`],
  [`Ensure <iframe> and <frame> elements contain a unique title attribute`, `Stellt sicher, dass <iframe> und <frame>-Elemente ein einzigartiges title-Attribut besitzen.`],
  [`Ensure <iframe> and <frame> elements have an accessible name`, `Stellt sicher, dass <iframe> und <frame>-Elemente ein nichtleeres title-Attribut besitzen.`],
  [`Ensure the order of headings is semantically correct`, `Stellt sicher, dass Überschriften in der semantisch korrekten Reihenfolge sind.`],
  [`Inform users about hidden content.`, `Informiert den Nutzer über versteckten Inhalt.`],
  [`Ensure every HTML document has a lang attribute`, `Stellt sicher, dass jedes HTML Dokument ein lang-Attribut besitzt.`],
  [`Ensure the lang attribute of the <html> element has a valid value`, `Stellt sicher, dass das lang-Attribut des <html>-Elements einen validen Wert besitzt.`],
  [`Ensure that HTML elements with both valid lang and xml:lang attributes agree on the base language of the page`, `Stellt sicher, dass HTML Elemente mit validen lang und xml:lang Attributen dieselbe Angabe über die Sprache machen.`],
  [`Ensure that links with the same accessible name serve a similar purpose`, `Stellt sicher, dass Links mit dem selben zugänglichen Namen (accessible name) denselben Zweck folgen.`],
  [`Ensure <img> elements have alternative text or a role of none or presentation`, `Stellt sicher, dass <img>-Elemente einen Alternativtext oder eine ARIA-Rolle mit dem Wert none oder presentation besitzen.`],
  [`Ensure image alternative is not repeated as text`, `Stellt sicher, dass Alternativtexte von Bildern nicht als Text wiederholt werden.`],
  [`Ensure input buttons have discernible text`, `Stellt sicher, dass Eingabeschaltflächen wahrnehmbaren Text beinhalten.`],
  [`Ensure <input type="image"> elements have alternative text`, `Stellt sicher, dass <input type="image">-Elemente einen Alternativtext besitzen.`],
  [`Ensure that elements labelled through their content must have their visible text as part of their accessible name`, `Stellt sicher, dass Elemente, die durch ihren Inhalt beschrieben sind, auch ihren sichtbaren Text als Teil des zugänglichen Namens (accessible name) haben.`],
  [`Ensure that every form element has a visible label and is not solely labeled using hidden labels, or the title or aria-describedby attributes`, `Stellt sicher, dass jedes <form>-Element nicht ausschließlich durch ein title oder aria-describedby-Attribut beschrieben sind.`],
  [`Ensure every form element has a label`, `Stellt sicher, dass jedes <form>-Element über eine Beschriftung verfügt.`],
  [`Ensure the banner landmark is at top level`, `Stellt sicher, dass die banner landmark sich auf der obersten Ebene befindet.`],
  [`Ensure the complementary landmark or aside is at top level`, `Stellt sicher, dass die ergänzende landmark oder aside sich auf dem höchsten Level befindet.`],
  [`Ensure the contentinfo landmark is at top level`, `Stellt sicher, dass die contentinfo landmark sich auf der obersten Ebene befindet.`],
  [`Ensure the main landmark is at top level`, `Stellt sicher, dass die main landmark sich auf der obersten Ebene befindet.`],
  [`Ensure the document has at most one banner landmark`, `Stellt sicher, dass das Dokument höchstens eine banner landmark besitzt.`],
  [`Ensure the document has at most one contentinfo landmark`, `Stellt sicher, dass das Dokument höchstens eine contentinfo landmark besitzt.`],
  [`Ensure the document has at most one main landmark`, `Stellt sicher, dass das Dokument höchstens eine main landmark besitzt.`],
  [`Ensure the document has a main landmark`, `Stellt sicher, dass das Dokument eine main landmark besitzt.`],
  [`Ensure landmarks are unique`, `Stellt sicher, dass landmarks einzigartig sind.`],
  [`Ensure links are distinguished from surrounding text in a way that does not rely on color`, `Stellt sicher, dass Links vom umgebenden Text nicht allein durch die Farbe unterschieden werden können.`],
  [`Ensure links have discernible text`, `Stellt sicher, dass Links wahrnehmbaren Text beinhalten.`],
  [`Ensure that lists are structured correctly`, `Stellt sicher, dass Listen korrekt strukturiert sind.`],
  [`Ensure <li> elements are used semantically`, `Stellt sicher, dass <li>-Elemente semantisch korrekt verwendet werden.`],
  [`Ensure <marquee> elements are not used`, `Stellt sicher, dass <marquee>-Elemente nicht verwendet werden.`],
  [`Ensure <meta http-equiv="refresh"> is not used for delayed refresh`, `Stellt sicher, dass <meta http-equiv="refresh"> nicht verwendet werden.`],
  [`Ensure <meta name="viewport"> can scale a significant amount`, `Stellt sicher, dass <meta name="viewport"> nicht verhindert, dass ein signifikanter Zoom verwendet werden kann.`],
  [`Ensure <meta name="viewport"> does not disable text scaling and zooming`, `Stellt sicher, dass <meta name="viewport"> Textskalierung und -zoom nicht verhindert werden.`],
  [`Ensure interactive controls are not nested as they are not always announced by screen readers or can cause focus problems for assistive technologies`, `Stellt sicher, dass interaktive Steuerelemente nicht verschachtelt (nested) sind, da sie nicht immer von Bildschirmlesegeräten angezeigt werden oder Probleme bei der Fokussierung von Hilfstechnologien verursachen können.`],
  [`Ensure <video> or <audio> elements do not autoplay audio for more than 3 seconds without a control mechanism to stop or mute the audio`, `Stellt sicher, dass <video> oder <audio> Elemente keine Töne automatisch abspielen für mehr als 3 Sekunden (autoplay) ohne eine Möglichkeit dies zu stoppen.`],
  [`Ensure <object> elements have alternative text`, `Stellt sicher, dass <object>-Elemente einen Alternativtext besitzen.`],
  [`Ensure bold, italic text and font-size is not used to style <p> elements as a heading`, `Stellt sicher, dass <p>-Elemente nicht dafür verwendet werden um Überschriften zu formatieren.`],
  [`Ensure that the page, or at least one of its frames contains a level-one heading`, `Stellt sicher, dass die Seite oder zumindest eins der frame-Elemente eine Überschrift der ersten Ebene enthalten.`],
  [`Ensure elements marked as presentational do not have global ARIA or tabindex so that all screen readers ignore them`, `Elemente mit role="none" oder role="presentation" sollten kein globales ARIA-Attribute besitzen oder fokussierbar sein, damit sie von Screenreadern ignoriert werden.`],
  [`Ensure all page content is contained by landmarks`, `Stellt sicher, dass jeglicher Inhalt in einer landmark region enthalten ist.`],
  [`Ensure [role="img"] elements have alternative text`, `Stellt sicher, dass [role='img'] Elemente einen Alternativ Text besitzen.`],
  [`Ensure the scope attribute is used correctly on tables`, `Stellt sicher, dass das scope-Attribut bei Tabellen korrekt verwendet wird.`],
  [`Ensure elements that have scrollable content are accessible by keyboard in Safari`, `Elemente, welche scrollbaren Inhalt besitzen sollten durch die Tastatur erreichbar und bedienbar sein.`],
  [`Ensure select element has an accessible name`, `Stellt sicher, dass <select> Elemente einen zugänglichen Namen (accessible name) besitzen.`],
  [`Ensure that server-side image maps are not used`, `Stellt sicher, dass serverseitige Imagemaps nicht verwendet werden.`],
  [`Ensure all skip links have a focusable target`, `Stellt sicher, dass alle Skip-Links ein fokussierbares Ziel enthalten.`],
  [`Ensure summary elements have discernible text`, `Stellt sicher, dass die summary-Elemente einen erkennbaren Text haben`],
  [`Ensure <svg> elements with an img, graphics-document or graphics-symbol role have accessible text`, `Stellt sicher, dass <svg> Elemente mit einer img, graphics-document oder graphics-symbol Rolle einen zugänglichen Namen (accessible name) besitzen.`],
  [`Ensure tabindex attribute values are not greater than 0`, `Stellt sicher, dass keine tabindex-Attribute mit einem Wert größer als null verwendet werden.`],
  [`Ensure the <caption> element does not contain the same text as the summary attribute`, `Stellt sicher, dass Tabellen nicht den gleichen Text im <caption>-Element wie im summary-Attribut enthalten.`],
  [`Ensure that tables with a caption use the <caption> element.`, `Stellt sicher, dass Tabellen mit einer Beschriftung auch das <caption>-Element verwenden.`],
  [`Ensure touch targets have sufficient size and space`, `Stellt sicher, dass Berührungsobjekte (touch targets) ausreichend groß sind und genügend Platz bieteen.`],
  [`Ensure that each non-empty data cell in a <table> larger than 3 by 3  has one or more table headers`, `Stellt sicher, dass jede nichtleere Zelle einer Tabelle ein oder mehrere Tabellenköpfe haben.`],
  [`Ensure that each cell in a table that uses the headers attribute refers only to other <th> elements in that table`, `Stellt sicher, dass jede Zelle in einer Tabelle, welche das headers-Attribut verwendet, sich nur auf andere Zellen derselben Tabelle beziehen.`],
  [`Ensure that <th> elements and elements with role=columnheader/rowheader have data cells they describe`, `Stellt sicher, dass jeder Tabellenkopf in einer Datentabelle sich auf Datenzellen bezieht.`],
  [`Ensure lang attributes have valid values`, `Stellt sicher, dass lang-Attribute gültige Werte haben.`],
  [`Ensure <video> elements have captions`, `Stellt sicher, dass <video>-Elemente Untertitel besitzen.`],
]);

const FAILURE_PREFIX_DE = {
  "any": {
    "failureMessage": "Korrigiere mindestens einen der folgenden Punkte:{{~it:value}}\n  {{=value.split('\\n').join('\\n  ')}}{{~}}"
  },
  "none": {
    "failureMessage": "Korrigiere alle der folgenden Punkte:{{~it:value}}\n  {{=value.split('\\n').join('\\n  ')}}{{~}}"
  }
} as Record<string, { failureMessage?: string }>;

/**
 * Translate the English `v.help` text that the scanner stored in scan_issues.description
 * back to German via axe-core's bundled de.json. Falls through to the input if no mapping
 * exists (handles rules added after this table was generated).
 */
export function translateAxeHelp(en: string | null | undefined): string {
  if (!en) return '';
  return HELP_EN_TO_DE.get(en) ?? en;
}

/**
 * Same but for axe rule descriptions (longer-form sentence beneath the help).
 */
export function translateAxeDescription(en: string | null | undefined): string {
  if (!en) return '';
  return DESCRIPTION_EN_TO_DE.get(en) ?? en;
}

/**
 * The `remediationHint` we stored is axe-core's node.failureSummary, which is a
 * multi-line block like:
 *   Fix any of the following:
 *     - Element has insufficient color contrast of 3.5
 *     - …
 * Translate the prefix lines via failureSummaries.de; check messages are kept as
 * stored because axe doesn't expose individual check translations by stable id
 * in a way we can reverse-match a stored sentence to. Better than nothing.
 */
export function translateAxeFailureSummary(en: string | null | undefined): string {
  if (!en) return '';
  let out = en;
  for (const key of Object.keys(FAILURE_PREFIX_DE)) {
    const def = FAILURE_PREFIX_DE[key];
    if (!def?.failureMessage) continue;
    // The English equivalents that axe-core uses as the prefix lines:
    const enAny = 'Fix any of the following:';
    const enAll = 'Fix all of the following:';
    if (key === 'any') out = out.replace(enAny, def.failureMessage);
    if (key === 'all' || key === 'none') out = out.replace(enAll, def.failureMessage);
  }
  return out;
}
